openapi: 3.0.3
info: { title: Demo API, version: 1.1.0 }
servers: [{ url: https://api.example.com }]
paths:
  /sites/{siteId}/custom-views:
    get:
      operationId: listCustomViews
      parameters:
        - in: path   # same
          name: siteId
          required: true
          schema: { type: string }
        - in: query  # same
          name: pageSize
          required: false
          schema: { type: integer, default: 100 }
        - in: query  # NEW
          name: includeSubsites
          required: false
          schema: { type: boolean }
      responses: { "200": { description: ok } }
  /sites/{siteId}/custom-views/{customViewId}/share: # NEW endpoint
    post:
      operationId: shareCustomView
      parameters:
        - in: path
          name: siteId
          required: true
          schema: { type: string }
        - in: path
          name: customViewId
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                principals: { type: array, items: { type: string } }
                capability: { type: string }
      responses: { "204": { description: shared } }# trigger14

# trigger

# Test workflow from main

