openapi: 3.0.3
info:
  title: Tableau Sites API
  version: 1.0.0
  description: Tableau REST API for managing sites
servers:
  - url: https://server/api/3.11
    description: Tableau Server
paths:
  /sites:
    post:
      operationId: createSite
      summary: Create Site
      description: Creates a new site
      parameters:
        - in: header
          name: X-Tableau-Auth
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                site:
                  type: object
                  properties:
                    name:
                      type: string
                    contentUrl:
                      type: string
                    adminMode:
                      type: string
      responses:
        '201':
          description: Site created successfully
    get:
      operationId: querySites
      summary: Query Sites
      description: Returns a list of sites
      parameters:
        - in: header
          name: X-Tableau-Auth
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 100
        - in: query
          name: pageNumber
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: List of sites
  /sites/{siteId}:
    delete:
      operationId: deleteSite
      summary: Delete Site by ID
      description: Deletes a site by ID
      parameters:
        - in: header
          name: X-Tableau-Auth
          required: true
          schema:
            type: string
        - in: path
          name: siteId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Site deleted successfully
    put:
      operationId: updateSite
      summary: Update Site
      description: Updates site information
      parameters:
        - in: header
          name: X-Tableau-Auth
          required: true
          schema:
            type: string
        - in: path
          name: siteId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                site:
                  type: object
                  properties:
                    name:
                      type: string
                    contentUrl:
                      type: string
      responses:
        '200':
          description: Site updated successfully
